// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLI0y_gvIvNxnymWd330BL6ECDLoN--1A',
    appId: '1:665826201076:web:3fe0b7876a1d733af37da1',
    messagingSenderId: '665826201076',
    projectId: 'movie-app-4ff23',
    authDomain: 'movie-app-4ff23.firebaseapp.com',
    storageBucket: 'movie-app-4ff23.firebasestorage.app',
    measurementId: 'G-34ZJ722103',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKvVENauUOD1ZBnPuMGBT_6gZq3i75alM',
    appId: '1:665826201076:android:cb740e1555d6538ef37da1',
    messagingSenderId: '665826201076',
    projectId: 'movie-app-4ff23',
    storageBucket: 'movie-app-4ff23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2dXwOkygkqi-Ha5jhSuvf77mBwPgd06Q',
    appId: '1:665826201076:ios:40ddf6ec64fa8391f37da1',
    messagingSenderId: '665826201076',
    projectId: 'movie-app-4ff23',
    storageBucket: 'movie-app-4ff23.firebasestorage.app',
    iosClientId: '665826201076-j2cp4rigavl4e2ou8k8hrhheru3piv0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.m',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2dXwOkygkqi-Ha5jhSuvf77mBwPgd06Q',
    appId: '1:665826201076:ios:40ddf6ec64fa8391f37da1',
    messagingSenderId: '665826201076',
    projectId: 'movie-app-4ff23',
    storageBucket: 'movie-app-4ff23.firebasestorage.app',
    iosClientId: '665826201076-j2cp4rigavl4e2ou8k8hrhheru3piv0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.m',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLI0y_gvIvNxnymWd330BL6ECDLoN--1A',
    appId: '1:665826201076:web:713f6e30d9ea5b20f37da1',
    messagingSenderId: '665826201076',
    projectId: 'movie-app-4ff23',
    authDomain: 'movie-app-4ff23.firebaseapp.com',
    storageBucket: 'movie-app-4ff23.firebasestorage.app',
    measurementId: 'G-9PF37TLEJC',
  );
}
